### ISSUE TITLE
PSR autoload is failing because of case insensitive namespace

### ISSUE THREAD

**Issue by flangfeldt** [FusionAuth/fusionauth-php-client#1]
## Expected behavior
FusionAuthClient class should autoload when used in code.

## Actual behavior
Autoloading is failing on a case sensitive file system. The declared namespace is **fusionauth**, but the directory holding the class is **FusionAuth**. Composer will look for the case sensitive directory **fusionauth** and will not find it.

## Possible solution
Rename the namespace in FusionAuthClient.php from **fusionauth** to **FusionAuth**.

**Comment by robotdan** [comment]
Will be available in next release.
