### ISSUE TITLE
PHP Login User Example Does Not Work

### ISSUE THREAD

**Issue by Alfrick** [FusionAuth/fusionauth-php-client#16]
The provided PHP login user example does not work for me.

Please assist me to solve it. 

He's my code:

$apiKey = "[mykey]";

$client = new FusionAuth\FusionAuthClient($apiKey, "http://localhost:9011/api/login");

$applicationId = "[myid]";

$request = array();
$request["applicationId"] = $applicationId;
$request["email"] = "oe@fusionauth.io";
$request["password"] = "12345";
$result = $client->login(json_encode($request));
if ($result->wasSuccessful()) {
 $user = json_encode($result->successResponse->user);
 echo $user;
}else{
   $user = json_encode($result->errorResponse);
 echo $user;
}

Here is the error I get:

{"fieldErrors":{"applicationId":[{"code":"[couldNotConvert]applicationId","message":"Invalid [applicationId]. This must be a valid UUID String (e.g. 25a872da-bb44-4af8-a43d-e7bcb5351ebc)."}],"loginId":[{"code":"[blank]loginId","message":"You must specify the [loginId] property."}],"password":[{"code":"[blank]password","message":"You must specify the [password] property."}],"userId":[{"code":"[couldNotConvert]userId","message":"Invalid userId on the URL [api]. This must be a valid UUID String (e.g. 25a872da-bb44-4af8-a43d-e7bcb5351ebc)."}]}}

Thanks.

**Comment by robotdan** [comment]
The JSON response indicates you are not sending in a valid UUID for the `applicationId` field, and you will want to use `loginId` instead of `email` in the JSON body. Did you find an example using `email` somewhere? 


```
{
  "fieldErrors": {
    "applicationId": [
      {
        "code": "[couldNotConvert]applicationId",
        "message": "Invalid [applicationId]. This must be a valid UUID String (e.g. 25a872da-bb44-4af8-a43d-e7bcb5351ebc)."
      }
    ],
    "loginId": [
      {
        "code": "[blank]loginId",
        "message": "You must specify the [loginId] property."
      }
    ],
    "password": [
      {
        "code": "[blank]password",
        "message": "You must specify the [password] property."
      }
    ],
    "userId": [
      {
        "code": "[couldNotConvert]userId",
        "message": "Invalid userId on the URL [api]. This must be a valid UUID String (e.g. 25a872da-bb44-4af8-a43d-e7bcb5351ebc)."
      }
    ]
  }
}
```

Your incoming JSON should look something like this
( https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user )

```
{
  "applicationId": "fbbf82ff-cc36-4540-aa30-578a57f12e61",
  "loginId": "oe@fusionauth.io",
  "password": "12345"
}
```

**Comment by Alfrick** [comment]
Thanks for your reply.

The email example is in the example code for [this PHP documentation](https://github.com/FusionAuth/fusionauth-php-client).

Even if I use the loginId instead of email in the JSON body, the error still persists.

If I echo the request array, it looks exactly [as this example](https://fusionauth.io/docs/v1/tech/apis/login#authenticate-a-user). 

It seems this issue occurs when implementing the FusionAuth PHP client for making POST requests. While making GET requests, such as [retrieveUserByEmail ](https://fusionauth.io/docs/v1/tech/client-libraries/php) works fine, POST requests return errors. 

Even the other POST requests seems to be having the same problem.

However, if I make POST requests using the FusionAuth API, without the PHP client library, everything works well.

**Comment by robotdan** [comment]
I'll see if I can recreate.

**Comment by robotdan** [comment]
Ah, I see your error.  Change your call from

```
$result = $client->login(json_encode($request));
```

to 

```
$result = $client->login($request);
```

the client handles the JSON encoding.  I've corrected the example in the README.

**Comment by Alfrick** [comment]
It works fine now.

Thanks!
