### ISSUE TITLE
getting invalid_redirect_uri

### ISSUE THREAD

**Issue by richb201** [FusionAuth/fusionauth-php-client#25]
I am working on a passwordless login script. The email to the user works fine. But when the user clicks on the link in the email he gets invalid_redirect_uri  (see image)
![Screenshot from 2021-04-28 07-56-41](https://user-images.githubusercontent.com/6951833/116399938-719ff080-a7f7-11eb-9cd4-b3a39abe3000.png)

Here is the uri as it appears in the email:
``
<a href="http://fusionauth.ngrok.io/oauth2/passwordless/DM4l8LlDvIGzDOcixtjgCMMsFX8-4GqMbsCPGC7k0Cs?tenantId=4272f95b-0989-4892-badc-0ef6b934885f&amp;client_id=f603697d-41ea-4c53-ac2d-e935d5e34221&amp;redirect_uri=35.153.28.164%2Findex.php%2FConfigure%2Freport_generator_amazing&amp;response_type=code&amp;scope=openid&amp;state=bandfrombossanova%40gmail.com" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://fusionauth.ngrok.io/oauth2/passwordless/DM4l8LlDvIGzDOcixtjgCMMsFX8-4GqMbsCPGC7k0Cs?tenantId%3D4272f95b-0989-4892-badc-0ef6b934885f%26client_id%3Df603697d-41ea-4c53-ac2d-e935d5e34221%26redirect_uri%3D35.153.28.164%252Findex.php%252FConfigure%252Freport_generator_amazing%26response_type%3Dcode%26scope%3Dopenid%26state%3Dbandfrombossanova%2540gmail.com&amp;source=gmail&amp;ust=1619697345074000&amp;usg=AFQjCNFvFntwmztFJBGSbqjC1o8nwwfa9A">
<button style="border:none;color:white;padding:15px 32px;text-align:center;text-decoration:none;font-size:16px;margin:4px 2px;background-color:#008cba">
Click Here to Login!
</button>
</a>
``

I am using docker and fusionauth/fusionauth-app:1.19.7.
Is the error message correct? How can I fix this?

**Comment by mooreds** [comment]
Hiya, this is a support query and should be asked in the forum (or with a support ticket if you have a paid edition with support). Closing.
