### ISSUE TITLE
Support php 8.1

### ISSUE THREAD

**Issue by sneakylenny** [FusionAuth/fusionauth-php-client#26]
Currently this library does not support PHP version 8.1.x
This has to do with breaking changes with some [deprecations](https://www.php.net/manual/en/migration81.deprecated.php) and [backward incompatible changes](https://www.php.net/manual/en/migration81.incompatible.php)

Versions 8.0.x and below **do** work without any problems.
For now I can't update my app to 8.1 since it is dependent on this library.

**Comment by mooreds** [comment]
Thanks for filing the issue. We'll look at creating a 8.1 library. You could also look at generating a library from the OpenAPI spec: https://github.com/fusionauth/fusionauth-openapi
