### ISSUE TITLE
Methods using the JWT authorization are failing

### ISSUE THREAD

**Issue by flangfeldt** [FusionAuth/fusionauth-php-client#3]
## Expected behavior
Calling any method using the JWT authorization should work just fine.

## Actual behavior
The JWT authorization header is added after the API key authorization header. Curl will only use the first header, thus ignoring the JWT authorization header.

## Possible solution
Replace any existing Authorization header when adding a new one.

**Comment by robotdan** [comment]
Will be available in next release.
